import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { CookiesProvider } from 'next-client-cookies/server';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OYO: India's Best Online Hotel Booking Site for Sanitized Stays",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.0.0/fonts/remixicon.css"
    rel="stylesheet"/>
    <link rel="icon"  href="https://www.oyorooms.com/favicon.ico"/>
      </head>
      <body className={inter.className} suppressHydrationWarning>
      <CookiesProvider>
        {children}
        </CookiesProvider>
      </body>
    </html>
  );
}
